/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.emp.gl.time.control;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.emp.gl.core.lookup.Lookup;
import org.emp.gl.robotservice.RobotServiceInterface;

/**
 *
 * @author ahmed
 */
public class GuiControl extends javax.swing.JFrame implements ActionListener  {

    /**
     * Creates new form GuiControl
     */
    public GuiControl() {
        initComponents();
        this.Leftbutton.addActionListener(this);
        this.rightbutton.addActionListener(this);
        this.uptbutton1.addActionListener(this);
        this.downtbutton2.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Leftbutton = new javax.swing.JButton();
        rightbutton = new javax.swing.JButton();
        comment = new javax.swing.JLabel();
        downtbutton2 = new javax.swing.JButton();
        uptbutton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Setting Robot");

        Leftbutton.setFont(new java.awt.Font("Algerian", 0, 25)); // NOI18N
        Leftbutton.setText("Left");
        Leftbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftbuttonActionPerformed(evt);
            }
        });

        rightbutton.setFont(new java.awt.Font("Algerian", 0, 25)); // NOI18N
        rightbutton.setText("right");
        rightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightbuttonActionPerformed(evt);
            }
        });

        comment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        downtbutton2.setFont(new java.awt.Font("Algerian", 0, 25)); // NOI18N
        downtbutton2.setText("down");
        downtbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downtbutton2ActionPerformed(evt);
            }
        });

        uptbutton1.setFont(new java.awt.Font("Algerian", 0, 25)); // NOI18N
        uptbutton1.setText("Up");
        uptbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uptbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Leftbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rightbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(downtbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uptbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(uptbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Leftbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(downtbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rightbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightbuttonActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_rightbuttonActionPerformed

    private void downtbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downtbutton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downtbutton2ActionPerformed

    private void LeftbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeftbuttonActionPerformed

    private void uptbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uptbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uptbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Leftbutton;
    private javax.swing.JLabel comment;
    private javax.swing.JButton downtbutton2;
    private javax.swing.JButton rightbutton;
    private javax.swing.JButton uptbutton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==this.Leftbutton)
        {
            
            Lookup.getInstance().getService(RobotServiceInterface.class).tourneLeft();
            
        }
         
        
        if(e.getSource()==this.rightbutton)
        {
            Lookup.getInstance().getService(RobotServiceInterface.class).tourneReight();
        }
        if(e.getSource()==this.uptbutton1)
        {
            
            Lookup.getInstance().getService(RobotServiceInterface.class).tourneUp();
            
        }
         
        
        if(e.getSource()==this.downtbutton2)
        {
            Lookup.getInstance().getService(RobotServiceInterface.class).tourneDown();
        }
        
    }
}
